language: node_js
node_js:
- 12
git:
  depth: false
addons:
 sauce_connect:
   username: "chimesdk"
   no_ssl_bump_domains: all
 jwt:
   secure: "Fs/jNys/0BYYFRLlHBWYWulAE4ydGp80f3eS1oewfUc6vYBo2+SGWyvchaattMn/5CoVdgIsrwj0A4OGXB2FJfkgiCENZ9LE+XVG1JWJIKPIe88VYrILVqsnPay9lTR7myVUUoDdtHDa+pO4h22BeEaIeJQGhmX5m8lVkjYdtVk76f0aW9SoN9sKNLQVARROvkqebMmFlzYuvbFkvmDohrz+alnAfrP/FFPdE9qN8ERm8G00qsOxLq3uxhJHadbKqG2aSOrhY+cyMJAXoDjojPVsWn1/0OUE4NXut6HLQXZJnq5m1Dw5U2DUOi4M/wcdaiWM6YM64HMPo4UchffSX4Tx8zdXfzhjnUjRYaHx3GMP2PK9HzFmnrOCuHsItly1/CaxlqOXnwEp4+YXGmdL7UR4HBxWcdJBDugPyfobIfusbC4aIVSoXrdt5HB2kPMmOdvRCnUJOFVHBVk3RMLQxhK5rFU3KlMsE3t4mOodY6kKkP9dihyuL3UyhCb/0g35cXBkJHTy16vYMWsx4rT4STmI0O+bGGPcNWpPvNUecDcxA0aVDrJTfpqzIGn9TPvhp7r2pV6nahu/mikjMSV6sYrtA66Vgsw+ddPgjXQPhPrREQrp6WOM9Ui16eRUPTTCS6pEU7N66TJN6dM08J1B5uFqWhIWdeOHkAwp/s5NhA0="
jobs:
  include:
    #Build and unit tests
    - stage: build
      if: (type = pull_request) OR (type = push AND branch != master)
      script: npm run build:release
      addons: skip
    #Integration tests
    - stage: integ_audio
      if: (type = pull_request) OR (type = push AND branch != master)
      before_install: script/needs-integration-test || travis_terminate 0
      install:
        - source script/travis-awscli-installation
        - integration/js/script/install-kite
      script: npm run test:integration-audio
    - stage: integ_video
      if: (type = pull_request) OR (type = push AND branch != master)
      before_install: script/needs-integration-test || travis_terminate 0
      install:
        - source script/travis-awscli-installation
        - integration/js/script/install-kite
      script: npm run test:integration-video
    - stage: integ_meeting_quit
      if: (type = pull_request) OR (type = push AND branch != master)
      before_install: script/needs-integration-test || travis_terminate 0
      install:
        - source script/travis-awscli-installation
        - integration/js/script/install-kite
      script: npm run test:integration-meeting-end
    - stage: integ_screen_share
      if: (type = pull_request) OR (type = push AND branch != master)
      before_install: script/needs-integration-test || travis_terminate 0
      install:
        - source script/travis-awscli-installation
        - integration/js/script/install-kite
      script: npm run test:integration-screen-share
    - stage: integ_content_share
      if: (type = pull_request) OR (type = push AND branch != master)
      before_install: script/needs-integration-test || travis_terminate 0
      install:
        - source script/travis-awscli-installation
        - integration/js/script/install-kite
      script: npm run test:integration-content-share
    - stage: integ_data_message
      if: (type = pull_request) OR (type = push AND branch != master)
      before_install: script/needs-integration-test || travis_terminate 0
      install:
        - source script/travis-awscli-installation
        - integration/js/script/install-kite
      script: npm run test:integration-data-message
    #Deploy
    - stage: deploy
      script: skip
      addons: skip
      install: source script/travis-awscli-installation
      deploy:
        provider: script
        script: script/deploy-canary-demo
        skip_cleanup: true
        on:
          branch: master
